# Generated by Django 5.1.6 on 2025-02-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(default="Anonymous", max_length=100)),
                ("user_message", models.TextField()),
                ("ai_response", models.TextField()),
                (
                    "model_used",
                    models.CharField(
                        choices=[
                            ("deepseek-r1:70b", "满血 DeepSeek"),
                            ("deepseek-r1", "蒸馏 DeepSeek"),
                        ],
                        default="deepseek-r1:70b",
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
